#%RAML 1.0
title: sn-s-packages-api
version: v1
protocols: [HTTPS]
mediaType: application/json

traits:
  clientIdEnforced: !include common/traits/clientIdEnforced.raml
  traceable: !include common/traits/traceable.raml

types:
  package: !include datatypes/package.raml

/packages:
  get:
      description: This API method is used to get all packages from application information repository.
      is: [clientIdEnforced, traceable]
      responses: 
        200:
          body: 
            application/json:
              type: package[]
              example: !include examples/package-list.json  

  